### ISSUE TITLE
Some errors in your docs

### ISSUE THREAD

**Issue by jpbsheppard** [amido/stacks#34]
![image](https://user-images.githubusercontent.com/19222967/85027383-c56e9180-b171-11ea-8ea5-4554e3ff173e.png)

On this page:
https://amido.github.io/stacks/docs/scaffolding_cli

![image](https://user-images.githubusercontent.com/19222967/85027704-1da59380-b172-11ea-8675-206603fa9e25.png)

https://amido.github.io/stacks/docs/cli_testing_frameworks

**Comment by estherthetesteramido** [comment]
Addressed in: https://github.com/amido/stacks/pull/35/files
