### ISSUE TITLE
Enhancement: Publish stacks nuget packages to a public Nuget repository

### ISSUE THREAD

**Issue by guibirow** [amido/stacks#4]
**Feature, tool or process you are suggesting improvement for:**

Stacks packages

**How you suggest to improve it:**

Currently, the nuget packages for stacks is hosted in a private feed in Azure DevOps and are downloaded using a PAT (Personal Access Token). This cause issues when the PAT token expires.
Because the project is private, we can't make the packages public.

This item requires internal approval, given the status of the project is still PRIVATE, until the project goes open source, we might need to keep the packages on a private repository.

**Comment by estherthetesteramido** [comment]
Closing this as complete. The PRs above relate to this work. Note that the packages are no longer being deployed with symbols.

The repo is still private.
